### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by NatsumiHB**
I went ahead and actually wrote the German translation, I hope I did this correctly ^^

### CODE REVIEW

**Comment by NatsumiHB** [comment]
I'd be willing to also update the translation with the newly added fields from #2

**Comment by gmaclennan** [comment]
Hi @NatsumiHB Thank you so much for this contribution! We actually just integrated a translations workflow using [CrowdIn](https://crowdin.com/project/mapeo-defaut-config). Sorry I did not update the README about this new process yet. I uploaded your translated strings to CrowdIn, so that the integration continues working correctly (if I were to merge this PR then CrowdIn would overwrite it with the data on the translation system).

If you would like to continue contributing translations you can do so here: https://crowdin.com/project/mapeo-defaut-config

I added German as a language for the app itself, if you are interested in contributing translations to that you can do so here: https://translate.mapeo.app/

Let me know your experience using CrowdIn via these links. This is new for us and I'd be interested to hear how it works for new users.

I'll close this PR since these changes are now in #6

**Comment by NatsumiHB** [comment]
I just now translated the last strings with CrowdIn and can say that it's been very pleasurable to work with. I'll definitely check out translating the actual mobile app too!

**Comment by gmaclennan** [comment]
Thanks so much @NatsumiHB 🥇

**Pull request closed without merging**
