### PR TITLE
chore: use Node 20

### PR DESCRIPTION
**Pull request by EvanHahn**
This required updating the npm lockfile.

We may want to do additional work in the future (e.g., testing on different Node versions), but I think this is worth doing now.

### CODE REVIEW

**Comment by tomasciccola** [comment]
Also I think there's a false positive on the CI. The `Build Asset` step actually fails

**Comment by gmaclennan** [comment]
yes, unfortunately the builder currently relies on Mapnik, and only works in Node 12.

**Comment by gmaclennan** [comment]
actually reading through the logs it looks like this is actually working, but it doesn't work on my machine (MacOS M1), so I think the errors might be due to mapnik not building on Apple Silicon, rather than node version.

**Comment by gmaclennan** [comment]
I'm thinking maybe to keep this on node12 for now, for the convenience of building locally for users with macOS

**Pull request closed without merging**
